version: '2.2'

services:

    openhab:
        image: openhab/openhab 
        container_name: openhab
        network_mode: host
  
    mosquitto:
        image: eclipse-mosquitto 
        container_name: mosquitto
        network_mode: host
  
    openhab-mqtt-api:
        image: openhab-mqtt-api 
        container_name: openhab-mqtt-api
        network_mode: host
        depends_on:
            - openhab
            - mosquitto