version: '1'

services:

    openhab:
        image: openhab/openhab
        container_name: openhab
  
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
  
    openhab-mqtt-api:
        image: openhab-mqtt-api
        container_name: openhab-mqtt-api
        depends_on:
            - openhab
            - mosquitto

build: 
    network: host