version: '2.2'

services:

    openhab:
        image: openhab/openhab:3.0.2
        container_name: openhab
        hostname: openhab
        devices:
            - "/dev/ttyACM0"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/opt/openhab/conf:/openhab/conf"
            - "/opt/openhab/userdata:/openhab/userdata"
            - "/opt/openhab/addons:/openhab/addons"
        environment:
            USER_ID: 998
            GROUP_ID: 997
            CRYPTO_POLICY: 'unlimited'
        network_mode: host
        restart: always
  
    mqtt-broker:
        image: eclipse-mosquitto:1.6.14
        container_name: mqtt-broker
        hostname: mqtt-broker
        ports:
            - 1883:1883
            - 9001:9001
        restart: unless-stopped
  
    openhab-mqtt:
        image: openhab-mqtt:latest
        environment:
            - OPENHAB_HOST_IP = 192.168.1.22
            - MQTT_HOST_IP = 192.168.1.22
        container_name: openhab-mqtt
        hostname: openhab-mqtt
        restart: unless-stopped
        depends_on:
            - openhab
            - mqtt-broker

