version: '2.2'

services:

    openhab:
        image: openhab/openhab:3.0.2
        container_name: openhab
        hostname: openhab
        devices:
            - "/dev/ttyACM0"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/opt/openhab/conf:/openhab/conf"
            - "/opt/openhab/userdata:/openhab/userdata"
            - "/opt/openhab/addons:/openhab/addons"
        environment:
            USER_ID: 999
            GROUP_ID: 995
            CRYPTO_POLICY: 'unlimited'
        network_mode: host
        restart: always
  
    mosquitto:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto
        hostname: mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        network_mode: host
        restart: unless-stopped
  
    openhab-mqtt:
        image: openhab-mqtt:latest
        container_name: openhab-mqtt
        hostname: openhab-mqtt
        network_mode: host
        restart: unless-stopped
        depends_on:
            - openhab
            - mosquitto

